In [1]:
%matplotlib inline
from keras.utils.vis_utils import plot_model
from keras.models import Model,Sequential
from tensorflow.keras.utils import to_categorical
from keras.layers import Input, Dense, Dropout
from tensorflow.keras.optimizers import SGD
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt  

In [2]:
data = pd.read_csv("dataset.csv")
data.head()

battery_power  blue  clock_speed  ...  touch_screen  wifi  price_range
0            842     0          2.2  ...             0     1            1
1           1021     1          0.5  ...             1     0            2
2            563     1          0.5  ...             1     0            2
3            615     1          2.5  ...             0     0            2
4           1821     1          1.2  ...             1     0            1

[5 rows x 21 columns]

In [3]:
print(data.shape)
train=[]
for i in range(data.shape[0]):
  train.append(list(data.iloc[i]))

(2000, 21)


In [4]:
x=[]
y=[]
for i in train:
  y.append(i[-1])
  x.append(i[:20])
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=29)


In [5]:
x_train = np.array(x_train)
y_train = np.array(y_train)
x_test = np.array(x_test)
y_test = np.array(y_test)
print(x_train)
print(y_train)

[[1.412e+03 1.000e+00 2.400e+00 ... 0.000e+00 0.000e+00 1.000e+00]
 [8.080e+02 1.000e+00 5.000e-01 ... 1.000e+00 0.000e+00 1.000e+00]
 [1.619e+03 1.000e+00 9.000e-01 ... 1.000e+00 0.000e+00 1.000e+00]
 ...
 [1.872e+03 1.000e+00 2.300e+00 ... 1.000e+00 0.000e+00 1.000e+00]
 [1.133e+03 0.000e+00 1.400e+00 ... 1.000e+00 0.000e+00 1.000e+00]
 [1.242e+03 1.000e+00 2.400e+00 ... 1.000e+00 0.000e+00 0.000e+00]]
[1. 0. 0. ... 2. 1. 0.]


In [6]:
y_train = to_categorical(y_train, 4)
y_test = to_categorical(y_test, 4)
print(y_test)

[[0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 ...
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [11]:
model = Sequential()
model.add(Dense(300, input_dim=x_train.shape[1], activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(200, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(150, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(50, activation='relu'))
model.add(Dense(4, activation='softmax'))
### YOU HAVE TO MAKE YOUR CHANGES HERE !!!


model.compile(optimizer = SGD(lr=0.001),
              loss = 'categorical_crossentropy',
              metrics=['accuracy'])

history = model.fit(x_train, y_train,
                    epochs=300,
                    batch_size=32,
                    verbose=1,
                    validation_data=(x_test,y_test))

/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/optimizer_v2.py:356: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  "The `lr` argument is deprecated, use `learning_rate` instead.")


Epoch 1/300
50/50 [==============================] - 3s 9ms/step - loss: 28.4573 - accuracy: 0.3350 - val_loss: 1.3846 - val_accuracy: 0.2425
Epoch 2/300
50/50 [==============================] - 0s 4ms/step - loss: 1.7022 - accuracy: 0.2988 - val_loss: 1.3069 - val_accuracy: 0.3450
Epoch 3/300
50/50 [==============================] - 0s 4ms/step - loss: 1.4612 - accuracy: 0.3512 - val_loss: 1.2810 - val_accuracy: 0.3650
Epoch 4/300
50/50 [==============================] - 0s 4ms/step - loss: 1.3879 - accuracy: 0.3700 - val_loss: 1.2792 - val_accuracy: 0.3675
Epoch 5/300
50/50 [==============================] - 0s 4ms/step - loss: 1.3490 - accuracy: 0.3819 - val_loss: 1.2362 - val_accuracy: 0.4000
Epoch 6/300
50/50 [==============================] - 0s 4ms/step - loss: 1.2781 - accuracy: 0.4106 - val_loss: 1.1283 - val_accuracy: 0.4600
Epoch 7/300
50/50 [==============================] - 0s 4ms/step - loss: 1.2799 - accuracy: 0.3994 - val_loss: 1.0903 - val_accuracy: 0.4675
Epoch 8/300


In [16]:
predict_x = model.predict(x_test)

In [19]:
classes_x=np.argmax(predict_x,axis=1)
classes_x

array([3, 3, 3, 1, 3, 3, 2, 3, 3, 0, 3, 0, 0, 3, 3, 3, 3, 3, 1, 1, 3, 2,
       2, 2, 2, 3, 1, 3, 3, 0, 0, 3, 3, 1, 0, 3, 0, 0, 2, 3, 1, 3, 2, 3,
       3, 0, 0, 3, 1, 3, 0, 3, 0, 3, 3, 0, 3, 3, 0, 2, 0, 1, 3, 0, 1, 3,
       2, 1, 1, 3, 1, 3, 3, 3, 0, 3, 3, 3, 3, 3, 3, 1, 2, 0, 3, 3, 3, 3,
       3, 1, 3, 3, 0, 1, 0, 1, 3, 3, 3, 2, 0, 1, 2, 3, 2, 2, 0, 3, 3, 0,
       3, 3, 3, 0, 3, 3, 3, 3, 2, 2, 3, 3, 0, 3, 0, 3, 0, 3, 3, 0, 2, 1,
       3, 3, 1, 0, 3, 0, 0, 3, 0, 1, 3, 0, 0, 0, 1, 2, 2, 3, 3, 2, 0, 2,
       2, 3, 3, 3, 0, 3, 1, 0, 3, 3, 3, 0, 3, 3, 0, 3, 0, 3, 3, 3, 3, 3,
       3, 1, 0, 0, 3, 1, 3, 3, 3, 3, 0, 3, 0, 3, 3, 2, 0, 1, 3, 3, 0, 1,
       1, 3, 3, 3, 3, 1, 3, 1, 3, 2, 0, 3, 0, 1, 3, 0, 0, 1, 2, 3, 3, 3,
       1, 3, 0, 3, 3, 3, 1, 2, 3, 3, 1, 1, 3, 2, 0, 0, 1, 3, 2, 0, 3, 3,
       3, 3, 1, 3, 3, 3, 0, 1, 2, 0, 3, 3, 2, 0, 3, 2, 0, 1, 0, 1, 1, 3,
       1, 0, 0, 0, 3, 3, 2, 3, 3, 3, 3, 0, 3, 3, 0, 3, 3, 3, 3, 3, 3, 0,
       3, 3, 3, 3, 3, 3, 3, 3, 0, 1, 3, 1, 3, 0, 0,

In [21]:
y_test_c = np.argmax(y_test,axis=1)
y_test_c

array([3, 2, 3, 1, 1, 3, 1, 3, 2, 0, 2, 0, 0, 1, 3, 3, 3, 3, 1, 1, 3, 1,
       2, 1, 1, 3, 1, 2, 1, 0, 1, 3, 3, 0, 0, 3, 0, 0, 2, 3, 1, 3, 2, 2,
       2, 0, 0, 1, 1, 2, 0, 2, 0, 3, 2, 0, 3, 1, 0, 1, 0, 0, 1, 0, 1, 3,
       2, 0, 0, 3, 1, 2, 3, 2, 0, 2, 3, 3, 2, 1, 3, 1, 2, 0, 3, 2, 2, 3,
       3, 1, 3, 2, 0, 1, 0, 1, 2, 3, 3, 0, 0, 1, 0, 2, 2, 2, 0, 3, 3, 0,
       2, 2, 1, 1, 1, 2, 1, 3, 1, 1, 2, 3, 0, 2, 0, 2, 0, 3, 3, 0, 2, 1,
       3, 2, 1, 1, 2, 0, 0, 3, 0, 1, 2, 0, 0, 0, 1, 1, 0, 2, 3, 1, 0, 1,
       2, 3, 1, 2, 0, 3, 1, 0, 2, 1, 2, 0, 3, 3, 0, 1, 0, 2, 3, 1, 3, 3,
       3, 1, 0, 0, 1, 1, 3, 3, 3, 1, 0, 1, 0, 2, 2, 1, 0, 0, 3, 3, 0, 1,
       1, 1, 2, 3, 3, 0, 3, 1, 2, 1, 0, 1, 0, 2, 1, 0, 0, 1, 2, 1, 3, 2,
       0, 3, 0, 3, 2, 3, 1, 2, 2, 3, 1, 1, 1, 2, 0, 0, 2, 1, 1, 0, 3, 3,
       3, 3, 1, 2, 2, 3, 0, 1, 2, 0, 2, 3, 1, 0, 3, 2, 0, 0, 0, 0, 1, 2,
       1, 0, 0, 0, 2, 1, 2, 1, 3, 3, 2, 1, 2, 3, 0, 3, 3, 3, 2, 3, 2, 0,
       3, 3, 3, 2, 1, 2, 3, 2, 1, 2, 1, 1, 3, 0, 0,

In [24]:
from sklearn import metrics

In [25]:
metrics.recall_score(y_test_c, classes_x, average='micro')

0.6175